[include AFC_menu.conf]

[main]
default_printer: Merc

[printer Merc]
titlebar_items: extruder,heater_bed,chamber

[menu __main favourites]
name: {{ gettext('Favourites') }}
icon: custom-script

[menu __main favourites clean_nozzle]
name: {{ gettext('Clean nozzle') }}
icon: extruder
enable: {{ printer.extruders.count > 0 }}
method: printer.gcode.script
params: {"script":"CLEAN_NOZZLE"}

[menu __main favourites toolhead_park]
name: {{ gettext('Park toolhead') }}
icon: stop
method: printer.gcode.script
params: {"script":"AFC_PARK"}

[menu __main favourites goto_center]
name: {{ gettext('Goto center') }}
icon: move
method: printer.gcode.script
params: {"script":"GOTO_CENTER"}

[menu __main favourites toggle_filtration]
name: {{ gettext('Toggle Air Filtration') }}
icon: fan-on
method: printer.gcode.script
params: {"script":"TOGGLE_FILTRATION"}

[menu __main favourites level_bed]
name: {{ gettext('Level bed') }}
icon: bed-level
method: printer.gcode.script
params: {"script":"LEVEL_BED"}

[menu __main favourites toggle_lights]
name: {{ gettext('Toggle lights') }}
icon: light
method: printer.gcode.script
params: {"script":"TOGGLE_LIGHTS"}

[menu __main favourites bt_eject_all]
name: {{ gettext('BT Eject All') }}
icon: toolchanger
method: printer.gcode.script
params: {"script":"BT_EJECT_ALL"}

[menu __main favourites shutdown_printer]
name: {{ gettext('Power off') }}
icon: shutdown
method: printer.gcode.script
params: {"script":"SHUTDOWN"}

[preheat cooldown]
heater_bed: 0
extruder: 0

[preheat ABS-T]
heater_bed: 105
extruder: 240
gcode:
   SET_FAN_SPEED FAN=rattrap SPEED=1.0

[preheat ASA]
heater_bed: 105
extruder: 250
gcode:
   SET_FAN_SPEED FAN=rattrap SPEED=1.0

[preheat PC]
heater_bed: 105
extruder: 285
gcode:
   SET_FAN_SPEED FAN=rattrap SPEED=1.0

[preheat PETG]
heater_bed: 90
extruder: 240

[preheat PLA]
heater_bed: 60
extruder: 210

[preheat TAP]
extruder: 150

#~# --- Do not edit below this line. This section is auto generated --- #~#
#~#
#~# [main]
#~# theme = material-darker
#~# side_shortcut_target = gcode_macros
#~# font_size = large
#~# move_speed_xy = 300
#~# print_sort_dir = date_desc
#~# print_view = list
#~# 
#~# [graph Merc]
#~# temperature_sensor raspberry_pi = False
#~# temperature_sensor mcu_temp = False
#~# temperature_sensor sht36-v2 = False
#~# temperature_sensor toolhead = False
#~# temperature_fan electronics_fan1 = False
#~# temperature_fan electronics_fan2 = False
#~# temperature_fan pi = False
#~# temperature_fan mcu = False
#~# temperature_sensor ebb36 = False
#~# temperature_sensor turtle_1 = False
#~# 
#~# [spoolman]
#~# hide_archived = False
#~#
